title: Stefandroid Blog
author: Stefan Thoss
description: This is Stefan's tech blog.
url: "https://blog.stefandroid.com"
github_username: stefanthoss
google_site_verification: IfD8jtnHx4mJpYOmj73jbGqeMSrR8K9C5AIUW6p0Uzs
show_excerpts: true

exclude:
  - "*.drawio"

header_pages:
  - about.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
