title: Stefandroid Blog
description: This is Stefan's tech blog.
url: "https://blog.stefandroid.com"
twitter_username: kabelknoten
github_username: stefanthoss
google_site_verification: IfD8jtnHx4mJpYOmj73jbGqeMSrR8K9C5AIUW6p0Uzs

theme: minima
show_excerpts: true

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
